### ISSUE TITLE
support for babel 7

### ISSUE THREAD

**Issue by seeden** [kristerkari/babel-plugin-react-native-classname-to-style#14]
Hi thanks for this great babel plugin.
Do you have any plan for babel 7?

**Comment by kristerkari** [comment]
Thanks @seeden! 

I guess I could already upgrade to Babel 7. Is there something that does not work or something else why it would be good to upgrade to Babel 7? Let me know and I'll upgrade!

**Comment by seeden** [comment]
Hi. I am using babel 7 in my web app. I have started to use react native in last few days and trying to convert my web version to native. I was just curious if you are thinking about support of new Babel. For native I am using babel 6.

**Comment by seeden** [comment]
Anyway thanks for this lib. I am using css modules and used <Text> <View> components in my whole web application. I did not realised that native is using style instead of className :)

**Comment by kristerkari** [comment]
okay, I see. :)

You can continue using Babel 7 in your web app, it should not conflict with the Babel version 6 that this plugin is using. 

I will update to Babel 7 at some point, so let's leave this issue open until then.

**Comment by seeden** [comment]
sounds good to me. thanks
